name     = "keys list"
services = [ "keys" ]
chain    = ""
steps    = [
  "eris services exec keys ls /home/eris/.eris/keys/data",
]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-actions"

[machine]
include = ["docker"]
requires = [""]
