# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "test_chain"
chain_id = "test_chain"

[service]
name = "test_chain"
data_container = true

[maintainer]
